language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  # Upgrade build dependencies to the latest version
  - pip install -U pip setuptools

  # Perform local installation of dymport
  - python setup.py develop

  # Install codecov package for codecov.io
  - pip install codecov

script:
  - python setup.py test

after_success:
  - codecov
